### Variables 
@apiurl = http://localhost:3000
@authToken = {{login.response.body.accessToken}}

//AUTH

### GET auth Google
GET {{apiurl}}/auth HTTP/1.1

### GET doctor Google
GET {{apiurl}}/auth/google-redirect HTTP/1.1

### POST login User
# @name login
POST {{apiurl}}/auth/login HTTP/1.1
Content-Type: application/json

{
   "email":"abbmr@hotmail.com",
   "password":"AnazinhaDaDoideira@23"
}

### POST verify token
POST {{apiurl}}/auth/token
Authorization: Bearer {{authToken}}

//USERS

### GET users
GET {{apiurl}}/user HTTP/1.1
Authorization: Bearer {{authToken}}

### POST users
POST {{apiurl}}/user HTTP/1.1
Content-Type: application/json

{
   "name":"Ana",
   "socialName":"",
   "lastName":"Beatrizete",
   "bornedAt":"1999/06/23",
   "email":"abbmr@hotmail.com",
   "cellphone": "(21)974331945",
   "password":"AnazinhaDaDoideira@23",
   "postalCode": "28940555",
   "city": "Santa Maria",
   "state": "RS",
   "street": "Redencio Frizzo",
   "maritalState":"SINGLE",
   "receiveNews": true
}

### PUT users
PUT {{apiurl}}/user/998572d0-a1c7-4eda-b080-561c2c08df40 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
   "name":"Ana",
   "socialName":"",
   "lastName":"Put",
   "bornedAt":"2004/02/03",
   "email":"abbmr1@gmail.com",
   "cellphone": "(21)974331945",
   "password":"Bobeirinha123@",
   "postalCode": "97770000",
   "city": "Santa Maria",
   "state": "RS",
   "street": "Redencio Frizzo",
   "maritalState":"SINGLE",
   "receiveNews": true
}

### PATCH users
PATCH {{apiurl}}/user/998572d0-a1c7-4eda-b080-561c2c08df40 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
   "name":"Ana Beatriz",
   "socialName":"",
   "lastName":"Patch",
   "bornedAt":"1999/06/23"
}


### GET users/doctors/:specialtyID
GET {{apiurl}}/user/doctors/1 HTTP/1.1
Authorization: Bearer {{authToken}}


//DOCTORS

### GET doctor
GET {{apiurl}}/doctor HTTP/1.1
Authorization: Bearer {{authToken}}

### GET doctor
GET {{apiurl}}/doctor/2f5e51e0-ec93-402d-9e3e-1d7681aa189e HTTP/1.1
Authorization: Bearer {{authToken}}

###PUT doctor
PUT {{apiurl}}/doctor/2f5e51e0-ec93-402d-9e3e-1d7681aa189e HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "name":"Ana",
   "socialName":"",
   "lastName":"Barreto",
   "bornedAt":"1985-09-16"

   }

###PATCH doctor
PATCH {{apiurl}}/doctor/6049c5e8-1415-44ce-af89-0a8310ab8615 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "name":"Tenali",
   "socialName":"",
   "lastName":"Ramakrishna",
   "bornedAt":"1985-09-16",
   "email":""
   }

### DELETE doctor
DELETE {{apiurl}}/doctor/6049c5e8-1415-44ce-af89-0a8310ab8615 HTTP/1.1
Authorization: Bearer {{authToken}}

//APPOINTMENTS

### GET appointments
GET {{apiurl}}/appointment HTTP/1.1
Authorization: Bearer {{authToken}}

### POST appointments
POST {{apiurl}}/appointment HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}
   
   {
      "doctorId":"2f5e51e0-ec93-402d-9e3e-1d7681aa189e",
      "userId":"afcf303b-a023-4eed-ad7d-2ba0a93c0d50",
      "scheduledAt":"2024-04-29T00:50:55.000Z",
      "status":"PENDING",
      "paymentMethod":"CREDIT_CARD"
   }


### GET appointments by user
GET {{apiurl}}/appointment/user/afcf303b-a023-4eed-ad7d-2ba0a93c0d50 HTTP/1.1
Accept-Type: application/json
Authorization: Bearer {{authToken}}


### GET appointments by doctor
GET {{apiurl}}/appointment/doctor/2f5e51e0-ec93-402d-9e3e-1d7681aa189e HTTP/1.1
Accept-Type: application/json
Authorization: Bearer {{authToken}}


### GET  all appointments
GET {{apiurl}}/appointment HTTP/1.1
Accept-Type: application/json
Authorization: Bearer {{authToken}}

### DELETE  appointment by ID

DELETE {{apiurl}}/appointment/3ac73499-17e4-411e-8d9e-f4b8ccfd2b3b HTTP/1.1
Accept-Type: application/json
Authorization: Bearer {{authToken}}

